services:
  barchetta-db:
    volumes:
      - ./src/main/resources/schema-nostr-mysql.sql:/docker-entrypoint-initdb.d/1.sql
    container_name: barchetta-mysqldb
    image: mysql:9.1.0
    ports:
      - "3326:3326"
    labels:
      org.springframework.boot.service-connection: mysql-servicecnxn-barchetta
    environment:
      MYSQL_DATABASE: barchetta
#      set below db name and credentials as desired
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluserpass
      MYSQL_ROOT_PASSWORD: mysqlrootuserpass
      MYSQL_TCP_PORT: 3326
    networks:
      docker-network:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "barchetta-mysqldb"]
      retries: 10
      interval: 3s
      timeout: 30s
  barchetta:
    container_name: barchetta-app
    image: barchetta:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
      - "5555:5555"
      - "443:443"
    depends_on:
      barchetta-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://barchetta-mysqldb:3326/barchetta
#      set below spring datasource parameters and credentials as desired
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqluserpass
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_SQL_INIT_MODE: always
    networks:
      docker-network:
volumes:
  barchetta-db:
    driver: local
networks:
  docker-network:
    driver: bridge
