spring.docker.compose.enabled=false

nostr.relay.uri=wss://localhost:5555

# wss autoconfigure
server.ssl.enabled=true
server.port=8080
server.ssl.bundle=server
spring.ssl.bundle.jks.server.key.alias=localhost
spring.ssl.bundle.jks.server.keystore.location=classpath:localhost.p12
spring.ssl.bundle.jks.server.keystore.password=changeit
spring.ssl.bundle.jks.server.keystore.type=PKCS12

#logging.pattern.console=%msg%n
spring.jpa.show-sql=true

# local non-container MySQL DB, temp for testing
spring.datasource.url=jdbc:mysql://localhost:3306/barchetta_nostr_dev
spring.sql.init.schema-locations=classpath:/schema-nostr-mysql.sql

# ----- common below
spring.datasource.username=mysqluser
spring.datasource.password=mysqluserpass

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always

### useful ancillary dev settings
#logging.level.root=TRACE
#logging.pattern.console=%msg%n

# cnxn test server
#nostr.relay.uri=ws://ws.vi-server.org/mirror
###