spring.profiles.active=@spring.profiles.active@

environmentlabel=Barchetta Smart-Contract Classifieds

barchetta.nostr.active=true
barchetta.uuid.prefix=barchetta_uuid-
barchetta.version=0.0.2-SNAPSHOT

#logging.level.web=trace

spring.security.user.name=configfileuser
spring.security.user.password=configfilepass
spring.security.user.roles=USER

# TODO: refactor below + ContractDefaultLoginHandler key=value into cad3 framework
barchetta.login.url.successful=/contract/display_all
#scd.login.url.failure=/error
