environmentlabel=Barchetta Smart-Contract Classifieds

barchetta.nostr.active=true
barchetta.version=0.0.1-SNAPSHOT
nostr.relay.uri=wss://localhost:5555
#logging.level.web=trace

# https & wss autoconfigure
server.ssl.enabled=true
server.port=8080
server.ssl.bundle=server
spring.ssl.bundle.jks.server.key.alias=localhost
spring.ssl.bundle.jks.server.keystore.location=classpath:localhost.p12
spring.ssl.bundle.jks.server.keystore.password=changeit
spring.ssl.bundle.jks.server.keystore.type=PKCS12

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=jpa_appuser
spring.datasource.password=jpa_appuserpass
spring.datasource.userSchemaDdlLocation=classpath:/users.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SECURITY - CORE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.security.user.name=configfileuser
spring.security.user.password=configfilepass
spring.security.user.roles=USER

# TODO: refactor below + ContractDefaultLoginHandler key=value into cad3 framework
barchetta.login.url.successful=/contract/display_all
#scd.login.url.failure=/error
